### PR TITLE
Classification problem, mushroom dataset

### PR DESCRIPTION
**Pull request by varun290101**
### Description

(Write your answer here.)

### Checklist

- [ ] I am making a proper pull request, not spam.
- [ ] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests

(Write your answer here.)

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by BlueBlaze6335** [comment]
@varun290101 very nice work !! Please update the notebook and the readme with the test accuracy in the same table and commit !! I will merge after that !!

**Comment by BlueBlaze6335** [comment]
@varun290101 please check the format of the readme mentioned above !!! Take help from the readme !! And also update the notebook !!

**Comment by varun290101** [comment]
Yes yes I am doing it

**Comment by BlueBlaze6335** [comment]
@varun290101 The one you got as accuracy is not test accuracy , they are the training accuracy !! test accuracy would be ```metrics.accuracy_score(y_test, y_pred)``` !!

**Comment by varun290101** [comment]
Okay bhaiya, sorry will change

**Comment by BlueBlaze6335** [comment]
Its okay bro !! You are learning !! Just add training accuracy - 100% , test accuracy - x (the one you will get ). And please try to adhere to the format of the README. It helps the viewers !!

**Comment by BlueBlaze6335** [comment]
Great Work !!!

**Pull request merged**
