### PR TITLE
Added Heart Disease Prediction using classification

### PR DESCRIPTION
**Pull request by Kasrazeba-Mulla**
### Description
Heart Disease Prediction -
Classification [Supervised Learning]

### Checklist

- [yes ] I am making a proper pull request, not spam.
- [ yes] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
Issue #5 

## Add relevant screenshot or video (if any)
Screenshot (378)

### CODE REVIEW

**Comment by BlueBlaze6335** [comment]
Hey @Kasrazeba-Mulla nice notebook !! Please save the readme in the correct format and remove the dataset from the directory. Name the folder Classification Heart Disease Dataset. And follow the format of the readme from other projects.

**Comment by Kasrazeba-Mulla** [comment]
@BlueBlaze6335 should i make a new pull request with the changes suggested by u?

**Comment by BlueBlaze6335** [comment]
Just edit the file , you will see how the datasets and their corresponding links are given. Add your dataset Name and link in that. As simple as that. And don't forget to add the link to the readme of your project too

**Comment by BlueBlaze6335** [comment]
please add model details to your readme !!

**Comment by BlueBlaze6335** [comment]
> Hey @Kasrazeba-Mulla nice notebook !! Please save the readme in the correct format and remove the dataset from the directory. Name the folder Classification Heart Disease Dataset. And follow the format of the readme from other projects.

I have clearly stated what needs to be done !! Your current version does not have any readme in it and the folder name is not correct !!

**Comment by Kasrazeba-Mulla** [comment]
Screenshot (380)
I have made commits for implementing the changes 
the readme file is updated with dataset link and model info and its format is markdown , the name of folder is changed acc. to ur suggestion

**Comment by Kasrazeba-Mulla** [comment]
@BlueBlaze6335 ok  i will do it . sorry its my first time ...

**Pull request closed without merging**
