### PR TITLE
Add the Project

### PR DESCRIPTION
**Pull request by TishaJhabak1014**
### Description

I have made the changes in the file .py, README.md and added the updated version of .ipynb nootbook.

### Checklist

- [x] I am making a proper pull request, not spam.
- [x] I've checked the issue list before deciding what to submit.

## Related Issues or Pull Requests
Please review.

## Add relevant screenshot or video (if any)

(Add here)

### CODE REVIEW

**Comment by TishaJhabak1014** [comment]
@sagnik1511 Raised a PR. Thank you.

**Comment by sagnik1511** [comment]
Thanks, @TishaJhabak1014! Nice work!!
Glance over other issues if you want to contribute more!

**Comment by sagnik1511** [comment]
Thanks, @TishaJhabak1014, happy contributing.
P.S. Do remember to add a line `Contributes to issue #<issue_number>`.

**Comment by TishaJhabak1014** [comment]
> Thanks, @TishaJhabak1014, happy contributing. P.S. Do remember to add a line `Contributes to issue #<issue_number>`.

Sorry, forgot by chance. Thank you.

**Comment by BlueBlaze6335** [comment]
@TishaJhabak1014 please save the results of your notebook and then submit a PR !! Your outputs are not showing in the notebook , and they are important because it is not showing the EDA or any plots to substantiate your work and according the updated the Result by Random forest is still the best. So check that and then submit your PR and inform me. This PR will not be considered !! Please be careful from the next time.

**Comment by TishaJhabak1014** [comment]
> @TishaJhabak1014 please save the results of your notebook and then submit a PR !! Your outputs are not showing in the notebook , and they are important because it is not showing the EDA or any plots to substantiate your work and according the updated the Result by Random forest is still the best. So check that and then submit your PR and inform me. This PR will not be considered !! Please be careful from the next time.

Yes, I will try to fix it asap.

**Comment by BlueBlaze6335** [comment]
You can also add other boosting algorithms or any other !! Do that if you want to and submit a PR !!

**Comment by TishaJhabak1014** [comment]
> You can also add other boosting algorithms or any other algorithm !! Do that if you want to and submit a PR !!
Okay, 

Also, can I add random-state parameter to every algorithm to ensure reproducibility?

**Comment by BlueBlaze6335** [comment]
Yes you can !! And also add brief description about the code cells using the text cells in the notebook and as comments in the python file !!

**Pull request merged**
